//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANFI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string RTL_Device {
            get {
                return ((string)(this["RTL_Device"]));
            }
            set {
                this["RTL_Device"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RTL_RTLAGC {
            get {
                return ((bool)(this["RTL_RTLAGC"]));
            }
            set {
                this["RTL_RTLAGC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RTL_TunerAGC {
            get {
                return ((bool)(this["RTL_TunerAGC"]));
            }
            set {
                this["RTL_TunerAGC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int RTL_TunerGain {
            get {
                return ((int)(this["RTL_TunerGain"]));
            }
            set {
                this["RTL_TunerGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[none]")]
        public string COM_Port {
            get {
                return ((string)(this["COM_Port"]));
            }
            set {
                this["COM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RTS")]
        public string COM_Noise {
            get {
                return ((string)(this["COM_Noise"]));
            }
            set {
                this["COM_Noise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DTR")]
        public string COM_DUT {
            get {
                return ((string)(this["COM_DUT"]));
            }
            set {
                this["COM_DUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public decimal RTL_SampleCount {
            get {
                return ((decimal)(this["RTL_SampleCount"]));
            }
            set {
                this["RTL_SampleCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public decimal RTL_SampleRate {
            get {
                return ((decimal)(this["RTL_SampleRate"]));
            }
            set {
                this["RTL_SampleRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COM_Port_Use {
            get {
                return ((bool)(this["COM_Port_Use"]));
            }
            set {
                this["COM_Port_Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COM_Noise_Use {
            get {
                return ((bool)(this["COM_Noise_Use"]));
            }
            set {
                this["COM_Noise_Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COM_DUT_Use {
            get {
                return ((bool)(this["COM_DUT_Use"]));
            }
            set {
                this["COM_DUT_Use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.4")]
        public double P_ENR {
            get {
                return ((double)(this["P_ENR"]));
            }
            set {
                this["P_ENR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RTL_GainMode {
            get {
                return ((int)(this["RTL_GainMode"]));
            }
            set {
                this["RTL_GainMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal Smoothing {
            get {
                return ((decimal)(this["Smoothing"]));
            }
            set {
                this["Smoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.45")]
        public decimal RTL_P_ENR {
            get {
                return ((decimal)(this["RTL_P_ENR"]));
            }
            set {
                this["RTL_P_ENR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public decimal DUT_Frequency {
            get {
                return ((decimal)(this["DUT_Frequency"]));
            }
            set {
                this["DUT_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DUT_P_ENR {
            get {
                return ((decimal)(this["DUT_P_ENR"]));
            }
            set {
                this["DUT_P_ENR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::CANFICore.MMODE Mode {
            get {
                return ((global::CANFICore.MMODE)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1275")]
        public decimal RTL_ClipValue_Max {
            get {
                return ((decimal)(this["RTL_ClipValue_Max"]));
            }
            set {
                this["RTL_ClipValue_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1275")]
        public decimal RTL_ClipValue_Min {
            get {
                return ((decimal)(this["RTL_ClipValue_Min"]));
            }
            set {
                this["RTL_ClipValue_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal RTL_MaxClipAllowed {
            get {
                return ((decimal)(this["RTL_MaxClipAllowed"]));
            }
            set {
                this["RTL_MaxClipAllowed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Noise_File_Activate {
            get {
                return ((bool)(this["Noise_File_Activate"]));
            }
            set {
                this["Noise_File_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Noise_FileName {
            get {
                return ((string)(this["Noise_FileName"]));
            }
            set {
                this["Noise_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RTL_Frequency_Min {
            get {
                return ((decimal)(this["RTL_Frequency_Min"]));
            }
            set {
                this["RTL_Frequency_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public decimal RTL_Frequency_Max {
            get {
                return ((decimal)(this["RTL_Frequency_Max"]));
            }
            set {
                this["RTL_Frequency_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DUT_Frequency_Min {
            get {
                return ((decimal)(this["DUT_Frequency_Min"]));
            }
            set {
                this["DUT_Frequency_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public decimal DUT_Frequency_Max {
            get {
                return ((decimal)(this["DUT_Frequency_Max"]));
            }
            set {
                this["DUT_Frequency_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>A;Measuring of Amplifiers in Direct Mode</string>
  <string>B;Measuring of Converters in Coverter Mode</string>
  <string>C;Measuring of Amplifiers with Converter Mode</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Modes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Modes"]));
            }
            set {
                this["Modes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal CAL_SampleCount_Min {
            get {
                return ((decimal)(this["CAL_SampleCount_Min"]));
            }
            set {
                this["CAL_SampleCount_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal CAL_SampleCount_Max {
            get {
                return ((decimal)(this["CAL_SampleCount_Max"]));
            }
            set {
                this["CAL_SampleCount_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RTL_AGC_Auto {
            get {
                return ((bool)(this["RTL_AGC_Auto"]));
            }
            set {
                this["RTL_AGC_Auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal RTL_SampleCount_Min {
            get {
                return ((decimal)(this["RTL_SampleCount_Min"]));
            }
            set {
                this["RTL_SampleCount_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public decimal RTL_SampleCount_Max {
            get {
                return ((decimal)(this["RTL_SampleCount_Max"]));
            }
            set {
                this["RTL_SampleCount_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COM_DUT_Inverse {
            get {
                return ((bool)(this["COM_DUT_Inverse"]));
            }
            set {
                this["COM_DUT_Inverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COM_Noise_Inverse {
            get {
                return ((bool)(this["COM_Noise_Inverse"]));
            }
            set {
                this["COM_Noise_Inverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CAL_Logging {
            get {
                return ((bool)(this["CAL_Logging"]));
            }
            set {
                this["CAL_Logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RTL_Logging {
            get {
                return ((bool)(this["RTL_Logging"]));
            }
            set {
                this["RTL_Logging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FFT_RealtimeDisplay {
            get {
                return ((bool)(this["FFT_RealtimeDisplay"]));
            }
            set {
                this["FFT_RealtimeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Smoothing_Min {
            get {
                return ((decimal)(this["Smoothing_Min"]));
            }
            set {
                this["Smoothing_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Smoothing_Max {
            get {
                return ((decimal)(this["Smoothing_Max"]));
            }
            set {
                this["Smoothing_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Values.csv")]
        public string RTL_Logging_FileName {
            get {
                return ((string)(this["RTL_Logging_FileName"]));
            }
            set {
                this["RTL_Logging_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibration.csv")]
        public string CAL_Logging_FileName {
            get {
                return ((string)(this["CAL_Logging_FileName"]));
            }
            set {
                this["CAL_Logging_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290")]
        public decimal Tamb {
            get {
                return ((decimal)(this["Tamb"]));
            }
            set {
                this["Tamb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290")]
        public decimal T0 {
            get {
                return ((decimal)(this["T0"]));
            }
            set {
                this["T0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal COM_Delay {
            get {
                return ((decimal)(this["COM_Delay"]));
            }
            set {
                this["COM_Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal RTL_Frequency_Step {
            get {
                return ((decimal)(this["RTL_Frequency_Step"]));
            }
            set {
                this["RTL_Frequency_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public decimal RTL_Frequency_Start {
            get {
                return ((decimal)(this["RTL_Frequency_Start"]));
            }
            set {
                this["RTL_Frequency_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public decimal RTL_Frequency_Stop {
            get {
                return ((decimal)(this["RTL_Frequency_Stop"]));
            }
            set {
                this["RTL_Frequency_Stop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FFT_Filter {
            get {
                return ((bool)(this["FFT_Filter"]));
            }
            set {
                this["FFT_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public object RTL_Devices {
            get {
                return ((object)(this["RTL_Devices"]));
            }
            set {
                this["RTL_Devices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RTL_DeviceIndex {
            get {
                return ((uint)(this["RTL_DeviceIndex"]));
            }
            set {
                this["RTL_DeviceIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144")]
        public decimal RTL_Frequency {
            get {
                return ((decimal)(this["RTL_Frequency"]));
            }
            set {
                this["RTL_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FFT_Filter_Threshold {
            get {
                return ((int)(this["FFT_Filter_Threshold"]));
            }
            set {
                this["FFT_Filter_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int FFT_Filter_NotchWidth {
            get {
                return ((int)(this["FFT_Filter_NotchWidth"]));
            }
            set {
                this["FFT_Filter_NotchWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NONE")]
        public global::CANFICore.SMODE SweepMode {
            get {
                return ((global::CANFICore.SMODE)(this["SweepMode"]));
            }
            set {
                this["SweepMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DUT_Frequency_Start {
            get {
                return ((decimal)(this["DUT_Frequency_Start"]));
            }
            set {
                this["DUT_Frequency_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DUT_Frequency_Stop {
            get {
                return ((decimal)(this["DUT_Frequency_Stop"]));
            }
            set {
                this["DUT_Frequency_Stop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DUT_Frequency_Step {
            get {
                return ((decimal)(this["DUT_Frequency_Step"]));
            }
            set {
                this["DUT_Frequency_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFTW")]
        public global::CANFICore.FFTALGORITHM FFT_Algorithm {
            get {
                return ((global::CANFICore.FFTALGORITHM)(this["FFT_Algorithm"]));
            }
            set {
                this["FFT_Algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.canfi.eu/downloads/rtlsdr.txt")]
        public string RTL_DLL_DownloadInfo_URL {
            get {
                return ((string)(this["RTL_DLL_DownloadInfo_URL"]));
            }
            set {
                this["RTL_DLL_DownloadInfo_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LICENSE")]
        public string Info_FileName {
            get {
                return ((string)(this["Info_FileName"]));
            }
            set {
                this["Info_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtlsdr.dll")]
        public string RTL_DLL_Win_FileName {
            get {
                return ((string)(this["RTL_DLL_Win_FileName"]));
            }
            set {
                this["RTL_DLL_Win_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("librtlsdr.so")]
        public string RTL_DLL_Lin_FileName {
            get {
                return ((string)(this["RTL_DLL_Lin_FileName"]));
            }
            set {
                this["RTL_DLL_Lin_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtlsdr")]
        public string RTL_DLL_DirName {
            get {
                return ((string)(this["RTL_DLL_DirName"]));
            }
            set {
                this["RTL_DLL_DirName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rtlsdr.zip")]
        public string RTL_DLL_Zip_FileName {
            get {
                return ((string)(this["RTL_DLL_Zip_FileName"]));
            }
            set {
                this["RTL_DLL_Zip_FileName"] = value;
            }
        }
    }
}
